apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/operator-framework/operator-lifecycle-manager.git
    targetRevision: v0.45.0
    path: deploy/upstream/quickstart
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
