---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform
  source:
    repoURL: https://github.com/infrasam/microshift-homelab.git
    targetRevision: main
    path: infrastructure/ingress-tls/overlays/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
