apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd-server
  namespace: argocd
spec:
  host: argocd.apps.k8slabs.se
  to:
    kind: Service
    name: argocd-server
  port:
    targetPort: http
  tls:
    termination: edge
