---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-apps
  namespace: openshift-ingress
spec:
  secretName: router-certs-default
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  dnsNames:
    - "*.apps.k8slabs.se"
