apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: monitoring
  namespace: monitoring
spec:
  targetNamespaces:
    - monitoring          # OwnNamespace: operatorn watch:ar bara sitt eget ns
